# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    networks:
      - app-net

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge